JSONConfigurer/urls.py
from django.contrib import admin
from django.urls import path, include

from django.views.decorators.csrf import csrf_exempt

from JSONConfigurer import views as views

app_name = "JSONConfigurer"
urlpatterns = [
  path('', views.home, name="home"),

  path('login/',                    views.loginPage,                name="login"),
  path('logout/',                   views.logoutPage,               name="logout"),
  path('register/',                 views.registerPage,             name="register"),

  # Camera URLS
  path('listCamera',                views.listCamera,               name="list-camera"),
  path('camera',                    views.createCamera,             name="create-camera"),
  path('camera/<int:id>',           views.camera,                   name="camera"),

  # Mission URLS
  path('listMission',               views.listMission,              name="list-mission"),
  path('mission',                   views.createMission,            name="create-mission"),
  path('mission/<int:id>',          views.mission,                  name="mission"),

  # General Configuration
  path('listConfigurations',       views.listConfigurations,        name="list-configuration"),
  path('configurations',           views.createConfiguration,       name="create-configuration"),
  path('configurations/<int:id>',  views.configuration,             name="configuration"),

  path('loadMission',               views.loadMissionFromFile,      name="load-mission"),
  path('loadGeneral',               views.loadGeneralFromFile,      name="load-general"),

  # # Slam URLS
  # path('listSlam',       views.listSlam,      name="list-slam"),
  # path('slam',           views.createSlam,     name="create-slam"),
  # path('slam/<int:id>',  views.slam,           name="slam"),
  #
  # # ORB URLS
  # path('listOrb',       views.listOrb,      name="list-orb"),
  # path('orb',           views.createOrb,     name="create-orb"),
  # path('orb/<int:id>',  views.orb,           name="orb"),
  #
  # # Viewer URLS
  # path('listViewer',       views.listViewer,      name="list-viewer"),
  # path('viewer',           views.createViewer,     name="create-viewer"),
  # path('viewer/<int:id>',  views.viewer,           name="viewer"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

from core.views import home

urlpatterns = [
    ## (Path, view function, pathName)
    path('', home, name="core-home"),
    path('admin/', admin.site.urls),

    # Including urlpatterns from JSONConfigurer app
    path("JSONConfigurer/", include("JSONConfigurer.urls")),
    path("Dashboard/", include("Dashboard.urls")),
]

JSONConfigurer/models.py
import os
from django.conf import settings
from django.db import models
from django.db.models import *

from django.urls import reverse

missionOpts = [
    ("Acceleration", "Acceleration"),
    ("Trackdrive", "Trackdrive"),
    ("Skidpad", "Skidpad"),
    ("none", "none"),
  ]

defPath = os.path.dirname(os.path.abspath(__file__))















# Create your models here.
class CameraModel(models.Model):
  name = models.CharField(max_length=200)

  fx = models.FloatField()
  fy = models.FloatField()
  cx = models.FloatField()
  cy = models.FloatField()

  k1 = models.FloatField()
  k2 = models.FloatField()
  p1 = models.FloatField()
  p2 = models.FloatField()

  width   = models.IntegerField()
  height  = models.IntegerField()
  fps     = models.IntegerField()

  bf      = models.FloatField()
  BGR_RGB     = models.BooleanField(default=True)
  THDepth = models.IntegerField()

  def get_absolute_url(self):
    return reverse("JSONConfigurer:camera", kwargs={"id": self.id})

  def __str__(self):
    return "{}_{}_{}_{}".format(self.name, self.width, self.height, self.fps)


















class MissionModel(models.Model):
  Note = models.CharField(max_length=500, blank=True)

  Mission = models.CharField(max_length=100, choices=missionOpts, default=missionOpts[0])

  Mapping = models.BooleanField(default=True)

  RectsBeforeTracking = models.BooleanField(default=True)

  NNThreaded = models.BooleanField(default=True)
  PCLThreaded = models.BooleanField(default=True)

  DatasetPath = models.CharField(max_length=300, default='/')

  Camera = models.ForeignKey(
    CameraModel,
    on_delete=models.CASCADE,
    null=True,
    )

  def get_absolute_url(self):
    return reverse("JSONConfigurer:mission", kwargs={"id": self.id})















class SlamModel(models.Model):
    RGB = BooleanField(default=True)
    ThDepth = IntegerField()
    DepthMapFactor = IntegerField()
    # def get_absolute_url(self):
    #   return reverse("JSONConfigurer:mission", kwargs={"id": self.id})
    def __str__(self):
        return "rgb:{},ThDepth:{},DepthMapFactor:{}".format(self.RGB, self.ThDepth, self.DepthMapFactor)















class ORBExtractorModel(models.Model):
    nFeautures = IntegerField()
    scaleFactor = FloatField()
    nLevels = IntegerField()
    iniThFAST = IntegerField()
    minThFAST = IntegerField()
    # def get_absolute_url(self):
    #   return reverse("JSONConfigurer:mission", kwargs={"id": self.id})
    def __str__(self):
        return "nFeatures:{},scaleFactor:{},nLevels{}".format(self.nFeautures, self.scaleFactor, self.nLevels)


















class ViewerModel(models.Model):
    KeyFrameSize = FloatField()
    KeyFrameLineWidth = FloatField()
    ReferenceSystemSize = FloatField()
    ReferenceSystemLineWidth = FloatField()
    GraphLineWidth = FloatField()
    PointSize = FloatField()
    CameraSize = FloatField()
    CameraLineWidth = FloatField()
    ViewpointX = FloatField()
    ViewpointY = FloatField()
    ViewpointZ = FloatField()
    ViewpointF = FloatField()

    def __str__(self):
        return "KFSize:{},KFLineWidth:{}".format(self.KeyFrameSize, self.KeyFrameLineWidth)


















class GeneralModel(models.Model):
    note = CharField(max_length=500, blank=True)

    Camera = ForeignKey(
        CameraModel,
        on_delete=models.CASCADE,
        null=True
    )
    SLAM = ForeignKey(
        SlamModel,
        on_delete=models.CASCADE,
        null=True
    )
    ORBExtractor = ForeignKey(
        ORBExtractorModel,
        on_delete=models.CASCADE,
        null=True
    )
    Viewer = ForeignKey(
        ViewerModel,
        on_delete=models.CASCADE,
        null=True
    )

    def get_absolute_url(self):
      return reverse("JSONConfigurer:configuration", kwargs={"id": self.id})

    def __str__(self):
        return "{}\r\nCamera: {}\r\nSlam: {}\r\nORB: {}\r\nViewer: {}".format(self.note, self.Camera, self.SLAM, self.ORBExtractor, self.Viewer)

JSONConfigurer/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms  import UserCreationForm

from django.utils.timezone import now
# Create your models here.

from .models import *


class CameraForm(forms.ModelForm):
    class Meta():
        model = CameraModel
        fields = "__all__"

class MissionForm(forms.ModelForm):
    class Meta():
        model = MissionModel
        fields = "__all__"

class UserForm(UserCreationForm):
    class Meta():
        model = User
        fields = [
            "username",
            "email",
            "password1",
            "password2"
        ]

class GeneralForm(forms.ModelForm):
    class Meta():
        model = GeneralModel
        fields = "__all__"

class SLAMForm(forms.ModelForm):
    class Meta():
        model = SlamModel
        fields = "__all__"

class ORBExtractorForm(forms.ModelForm):
    class Meta():
        model = ORBExtractorModel
        fields = "__all__"

class ViewerForm(forms.ModelForm):
    class Meta():
        model = ViewerModel
        fields = "__all__"

JSONConfigurer/views.py
from django.utils import timezone
from django.views.generic.list import ListView
from django.shortcuts import render, get_object_or_404, redirect

from django.http import JsonResponse, StreamingHttpResponse, FileResponse, HttpResponse
from django.contrib.auth.forms import UserCreationForm

from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from django.utils.html import escape

from .models import *
from .forms  import *

from .scripts.parser import *
from .scripts.load   import *

def home(req):
  return render(req, 'JSONHome.html', {})

#---------------------------------------------------#
## Login-Register
#---------------------------------------------------#

def loginPage(req):
  if req.user.is_authenticated:
    return redirect("JSONConfigurer:home")

  if req.method == "POST":
    username = req.POST.get("username")
    password = req.POST.get("password")

    user = authenticate(req, username=username, password=password)

    if not user == None:
      login(req, user)
      return redirect("JSONConfigurer:home")
    else:
      messages.info(req, "Username or password incorrect")

  context = {}
  return render(req, "user/login.html", context)

def registerPage(req):
  if req.user.is_authenticated:
    return redirect("JSONConfigurer:home")

  form  = UserForm(req.POST or None)

  if form.is_valid():
    form.save()
    return redirect('JSONConfigurer:login')

  context = {"form": form}
  return render(req, "user/register.html", context)

def logoutPage(req):
  logout(req)

  return redirect('JSONConfigurer:login')


#---------------------------------------------------#
## Camera
#---------------------------------------------------#

# List of all camera
# Allow to select and then edit
def listCamera(req):

  camera = CameraModel.objects.all()

  context = {
    "data": camera
  }

  return render(req, 'camera/listCamera.html', context)

# Blank form to be filled and saved
@login_required(login_url="JSONConfigurer:login")
def createCamera(req):

  mCamera = CameraForm(req.POST or None)

  if mCamera.is_valid():
    mCamera.save()

  context = {
    "camera": mCamera
  }
  return render(req, 'camera/camera.html', context)

# Detail of a camera
# Allow to edit delete or download camera
@login_required(login_url="JSONConfigurer:login")
def camera(req, id):
  print(req)
  print(req.GET)
  print(req.POST)
  print(req.user)
  print(escape(repr(req)))
  camera = get_object_or_404(CameraModel, pk=id)

  mCamera = CameraForm(req.POST or None, instance=camera)

  keys = req.POST

  # Download button in camera.html
  if keys.get("download") == "Download":
    # Generating the yaml and saving it to a temp file
    filename = convertCameraToYaml(camera)

    # Downloading the file
    response = HttpResponse(open(filename, 'rb').read())
    response['Content-Type'] = 'text/plain'
    response['Content-Disposition'] = 'attachment; filename={}'.format(filename)
    return response

  # Save button in camera.html
  elif keys.get("submit") == "Save":
    if mCamera.is_valid():
      mCamera.save()
      return redirect("JSONConfigurer:list-camera")

  # Delete button in camera.html
  # Rendering the confirmation page
  elif keys.get("submit") == "Delete":
    return render(req, 'delete.html', {})

  # Delete button in delete.html (confirmation Page)
  elif keys.get("delete") == "Yes":
    camera.delete()
    return redirect("JSONConfigurer:list-camera", permanent=True)
  # Delete button in delete.html (confirmation Page)
  elif keys.get("delete") == "No":
    mCamera = CameraForm(None, instance=camera)

  context = {
    "camera": mCamera
  }
  return render(req, 'camera/camera.html', context)


#---------------------------------------------------#
## Mission
#---------------------------------------------------#

# List of all missions in DB
# Allow to enter in detail of the selected one
def listMission(req):

  missions = MissionModel.objects.all()

  context = {
    "data": missions
  }

  return render(req, 'mission/listMission.html', context)


# Blank Mission to be filled and saved
@login_required(login_url="JSONConfigurer:login")
def createMission(req):

  mMission = MissionForm(req.POST or None)

  if mMission.is_valid():
    mMission.save()

  context = {
    "mission": mMission
  }

  return render(req, 'mission/mission.html', context)

# Detail of a mission
# Allow to edit delete or download mission
@login_required(login_url="JSONConfigurer:login")
def mission(req, id):
  mission = get_object_or_404(MissionModel, id=id)

  mMission = MissionForm(req.POST or None, instance=mission)

  keys = req.POST
  # Download button in mission.html
  if keys.get("download") == "Download":
    # Converting all the model to JSON
    filename = convertMissionToJson(mission)
    # Dowloading the file
    response = HttpResponse(open(filename, 'rb').read())
    response['Content-Type'] = 'text/plain'
    response['Content-Disposition'] = 'attachment; filename={}'.format(filename)
    return response

  # Save button in mission.html
  elif keys.get("submit") == "Save":
    if mMission.is_valid():
      # Saving/Updatind mission
      mMission.save()
      return redirect("JSONConfigurer:list-mission")

  # Delete button in mission.html
  elif keys.get("submit") == "Delete":
    return render(req, 'delete.html', {})

  # Delete confirmation button in delete.html
  elif keys.get("delete") == "Yes":
    mission.delete()
    return redirect("JSONConfigurer:list-mission", permanent=True)

  # Delete confirmation button in delete.html
  elif keys.get("delete") == "No":
    # Resetting the form to the existing instance
    mMission = MissionForm(None, instance=mission)

  context = {
    "mission": mMission
  }

  return render(req, 'mission/mission.html', context)


#---------------------------------------------------#
## Slam
#---------------------------------------------------#

#---------------------------------------------------#
## ORB
#---------------------------------------------------#

#---------------------------------------------------#
## Viewer
#---------------------------------------------------#

#---------------------------------------------------#
## General Configuration
#---------------------------------------------------#
def listConfigurations(req):
    configurations = GeneralModel.objects.all()

    context = {
      "data": configurations
    }
    return render(req, "configuration/listConfiguration.html", context)

@login_required(login_url="JSONConfigurer:login")
def createConfiguration(req):
  mGeneral = GeneralForm(req.POST or None)

  if mGeneral.is_valid():
    mGeneral.save()

  context = {
    "configuration": mGeneral
  }
  return render(req, "configuration/configuration.html", context)

@login_required(login_url="JSONConfigurer:login")
def configuration(req, id):

  configuration = get_object_or_404(GeneralModel, id=id)

  mConfiguration = GeneralForm(req.POST or None, instance=configuration)

  keys = req.POST
  # Download button in mission.html
  if keys.get("download") == "Download":
    # Converting all the model to JSON
    filename = convertGeneralToJson(configuration)
    # Dowloading the file
    response = HttpResponse(open(filename, 'rb').read())
    response['Content-Type'] = 'text/plain'
    response['Content-Disposition'] = 'attachment; filename={}'.format(filename)
    return response

  # Save button in mission.html
  elif keys.get("submit") == "Save":
    if mConfiguration.is_valid():
      # Saving/Updatind mission
      mConfiguration.save()
      return redirect("JSONConfigurer:list-configuration")

  # Delete button in mission.html
  elif keys.get("submit") == "Delete":
    return render(req, 'delete.html', {})

  # Delete confirmation button in delete.html
  elif keys.get("delete") == "Yes":
    configuration.delete()
    return redirect("JSONConfigurer:list-confirmation", permanent=True)

  # Delete confirmation button in delete.html
  elif keys.get("delete") == "No":
    # Resetting the form to the existing instance
    mMission = GeneralForm(None, instance=configuration)

  context = {
    "configuration": mConfiguration
  }

  return render(req, "configuration/configuration.html", context)


#---------------------------------------------------#
## Load Configurations From File
#---------------------------------------------------#
def loadMissionFromFile(req):
    if req.method == "POST":
        mFile = req.FILES.get("file")
        if loadMission(mFile):
            return redirect("JSONConfigurer:list-mission")

    context = {}
    return render(req, "load.html", context)

def loadGeneralFromFile(req):
    if req.method == "POST":
        mFile = req.FILES.get("file")
        if loadGeneral(mFile):
            return redirect("JSONConfigurer:list-configuration")

    context = {}
    return render(req, "load.html", context)

JSONConfigurer/templates/JSONHome.html
{%extends 'JSONConfigurer.html' %}

{% load static %}

{%block content%}


<div class="masthead bg-primary text-white text-center">
    <h1 class="masthead-heading text-uppercase mb-0">JSON Configurer</h1>
</div>

<!--
<div class="divider-custom mt-4">
    <div class="divider-custom-line"></div>
    <div class="divider-custom-line"></div>
</div>

<div class="container d-flex align-items-center flex-column">
  <a class="btn btn-primary btn-xl m-2" href="{% url 'JSONConfigurer:list-camera' %}">Camere</a>
  <div class="divider-custom mt-4">
      <div class="divider-custom-line"></div>
      <div class="divider-custom-line"></div>
  </div>
  <a class="btn btn-primary btn-xl m-2" href="{% url 'JSONConfigurer:list-mission' %}">Mission</a>
  <div class="divider-custom mt-4">
      <div class="divider-custom-line"></div>
      <div class="divider-custom-line"></div>
  </div>
</div>
-->

<!-- Portfolio Section-->
  <section class="page-section portfolio" id="portfolio">
      <div class="container">
          <!-- grid Items-->
          <div class="row justify-content-center">
            <!-- Item 1-->
            <div class="col-md-6 col-lg-4">
              <a class="nav-link py-3 px-0 px-lg-3 rounded"
                  href="{% url 'JSONConfigurer:list-mission' %}">
                <div class="portfolio-item mx-auto">
                    <div class="portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100">
                        <div class="portfolio-item-caption-content text-center text-white"><i class="fas fa-plus fa-3x"></i></div>
                    </div>
                    <div class="text-center c1">
                      <i class="fas fa-bolt fa-6x"></i>
                      <h3>
                        Mission
                      </h3>
                    </div>
                </div>
                </a>
            </div>

            <!-- Item 2-->
            <div class="col-md-6 col-lg-4">
              <a class="nav-link py-3 px-0 px-lg-3 rounded"
                  href="{% url 'JSONConfigurer:list-configuration' %}">
                <div class="portfolio-item mx-auto">
                    <div class="portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100">
                        <div class="portfolio-item-caption-content text-center text-white"><i class="fas fa-plus fa-3x"></i></div>
                    </div>
                    <div class="text-center c2">
                      <i class="fas fa-database fa-6x"></i>
                      <h3>
                        General
                      </h3>
                    </div>
                </div>
                </a>
            </div>

            <!-- Item 3-->
            <div class="col-md-6 col-lg-4">
              <a class="nav-link py-3 px-0 px-lg-3 rounded"
                  href="{% url 'JSONConfigurer:list-camera' %}">
                <div class="portfolio-item mx-auto">
                    <div class="portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100">
                        <div class="portfolio-item-caption-content text-center text-white"><i class="fas fa-plus fa-3x"></i></div>
                    </div>
                    <div class="text-center c3">
                      <i class="fas fa-camera fa-6x"></i>
                      <h3>
                        Camera
                      </h3>
                    </div>
                </div>
                </a>
            </div>

            <!-- Item 3-->
            <div class="col-md-6 col-lg-4">
              <a class="nav-link py-3 px-0 px-lg-3 rounded"
                  href="{% url 'JSONConfigurer:list-configuration' %}">
                <div class="portfolio-item mx-auto">
                    <div class="portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100">
                        <div class="portfolio-item-caption-content text-center text-white"><i class="fas fa-plus fa-3x"></i></div>
                    </div>
                    <div class="text-center c4">
                      <i class="fas fa-map fa-6x"></i>
                      <h3>
                        Slam
                      </h3>
                    </div>
                </div>
                </a>
            </div>

            <!-- Item 3-->
            <div class="col-md-6 col-lg-4">
              <a class="nav-link py-3 px-0 px-lg-3 rounded"
                  href="{% url 'JSONConfigurer:list-configuration' %}">
                <div class="portfolio-item mx-auto">
                    <div class="portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100">
                        <div class="portfolio-item-caption-content text-center text-white"><i class="fas fa-plus fa-3x"></i></div>
                    </div>
                    <div class="text-center c5">
                      <i class="fas fa-dot-circle fa-6x"></i>
                      <h3>
                        ORB
                      </h3>
                    </div>
                </div>
                </a>
            </div>

            <!-- Item 3-->
            <div class="col-md-6 col-lg-4">
              <a class="nav-link py-3 px-0 px-lg-3 rounded"
                  href="{% url 'JSONConfigurer:list-configuration' %}">
                <div class="portfolio-item mx-auto">
                    <div class="portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100">
                        <div class="portfolio-item-caption-content text-center text-white"><i class="fas fa-plus fa-3x"></i></div>
                    </div>
                    <div class="text-center c6">
                      <i class="fas fa-laptop fa-6x"></i>
                      <h3>
                        Viewer
                      </h3>
                    </div>
                </div>
                </a>
            </div>

            <!-- Item 7-->
            <div class="col-md-6 col-lg-4">
              <a class="nav-link py-3 px-0 px-lg-3 rounded"
                  href="{% url 'JSONConfigurer:load-mission' %}">
                <div class="portfolio-item mx-auto">
                    <div class="portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100">
                        <div class="portfolio-item-caption-content text-center text-white"><i class="fas fa-plus fa-3x"></i></div>
                    </div>
                    <div class="text-center c1 ">
                      <i class="fas fa-upload fa-6x"></i>
                      <h3>
                        LoadMission
                      </h3>
                    </div>
                </div>
                </a>
            </div>

            <!-- Item 8-->
            <div class="col-md-6 col-lg-4">
              <a class="nav-link py-3 px-0 px-lg-3 rounded"
                  href="{% url 'JSONConfigurer:load-general' %}">
                <div class="portfolio-item mx-auto">
                    <div class="portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100">
                        <div class="portfolio-item-caption-content text-center text-white"><i class="fas fa-plus fa-3x"></i></div>
                    </div>
                    <div class="text-center c2 ">
                      <i class="fas fa-upload fa-6x"></i>
                      <h3>
                        LoadGeneral
                      </h3>
                    </div>
                </div>
                </a>
            </div>


          </div>
      </div>
  </section>

{%endblock content%}

JSONConfigurer/templates/delete.html
{%extends 'JSONConfigurer.html' %}

{%block content%}

<div class="masthead bg-primary text-white text-center">
    <h1 class="masthead-heading text-uppercase mb-0">Elimina</h1>
</div>

<div class="container d-flex align-items-center flex-column">
  <div class="container d-flex align-items-center flex-column mt-3r">

    <form method="POST">{% csrf_token %}
      <input type="submit" name="delete" value="Yes" />
      <input type="submit" name="delete" value="No" />
    </form>

  </div>
</div>

{%endblock content%}

JSONConfigurer/templates/load.html
{%extends 'JSONConfigurer.html' %}

{%block content%}

<div class="masthead bg-primary text-white text-center">
    <h1 class="masthead-heading text-uppercase mb-0">Upload</h1>
</div>

<div class="container d-flex align-items-center flex-column">
  <div class="container d-flex align-items-center flex-column mt-3r">

    {% if request.user.is_staff %}
    <form method="POST" enctype="multipart/form-data">{% csrf_token %}
        <input type="file" name="file" />
        <input type="submit" name="submit" value="Upload" />
      </form>
    {% else %}
    <p>
      Sorry, this area is accessible only for staff
    </p>
    {% endif %}
  </div>
</div>

{%endblock content%}