Dashboard/urls.py
from django.urls import path, include

from django.views.decorators.csrf import csrf_exempt

from Dashboard import views as views

app_name = "Dashboard"
urlpatterns = [
  path('', views.home, name="home"),

  path('view/<int:id>', views.view, name="view"),

  path('database',             views.database, name="database"),
  path('realTime',             views.real_time, name="real-time"),
  path('realTime/setData', csrf_exempt(views.rt_set_data), name="rt-set-data"),
  path('realTime/getData/<slug:sensor>', csrf_exempt(views.rt_get_data), name="rt-get-data"),

  path('getData',             views.get_data, name="get-data"),
  path('setData', csrf_exempt(views.set_data), name="set-data"),
]

JSONConfigurer/urls.py
from django.contrib import admin
from django.urls import path, include

from django.views.decorators.csrf import csrf_exempt

from JSONConfigurer import views as views

app_name = "JSONConfigurer"
urlpatterns = [
  path('', views.home, name="home"),

  path('login/',                    views.loginPage,                name="login"),
  path('logout/',                   views.logoutPage,               name="logout"),
  path('register/',                 views.registerPage,             name="register"),

  # Camera URLS
  path('listCamera',                views.listCamera,               name="list-camera"),
  path('camera',                    views.createCamera,             name="create-camera"),
  path('camera/<int:id>',           views.camera,                   name="camera"),

  # Mission URLS
  path('listMission',               views.listMission,              name="list-mission"),
  path('mission',                   views.createMission,            name="create-mission"),
  path('mission/<int:id>',          views.mission,                  name="mission"),

  # General Configuration
  path('listConfigurations',       views.listConfigurations,        name="list-configuration"),
  path('configurations',           views.createConfiguration,       name="create-configuration"),
  path('configurations/<int:id>',  views.configuration,             name="configuration"),

  path('loadMission',               views.loadMissionFromFile,      name="load-mission"),
  path('loadGeneral',               views.loadGeneralFromFile,      name="load-general"),

  # # Slam URLS
  # path('listSlam',       views.listSlam,      name="list-slam"),
  # path('slam',           views.createSlam,     name="create-slam"),
  # path('slam/<int:id>',  views.slam,           name="slam"),
  #
  # # ORB URLS
  # path('listOrb',       views.listOrb,      name="list-orb"),
  # path('orb',           views.createOrb,     name="create-orb"),
  # path('orb/<int:id>',  views.orb,           name="orb"),
  #
  # # Viewer URLS
  # path('listViewer',       views.listViewer,      name="list-viewer"),
  # path('viewer',           views.createViewer,     name="create-viewer"),
  # path('viewer/<int:id>',  views.viewer,           name="viewer"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

from core.views import home

urlpatterns = [
    ## (Path, view function, pathName)
    path('', home, name="core-home"),
    path('admin/', admin.site.urls),

    # Including urlpatterns from JSONConfigurer app
    path("JSONConfigurer/", include("JSONConfigurer.urls")),
    path("Dashboard/", include("Dashboard.urls")),
]

Dashboard/models.py
from django.db import models
from django.db.models.base import Model

from django.urls import reverse

# Create your models here.


class DataModel(models.Model):
    name = models.CharField(max_length=200)
    data = models.CharField(max_length=10485700)

    def get_absolute_url(self):
        return reverse("Dashboard:view", kwargs={"id": self.id})


class RealTimeModel(models.Model):
    name = models.CharField(max_length=200)
    data = models.CharField(max_length=10485700)
    timestamp = models.CharField(max_length=200)

    def get_absolute_url(self):
        return reverse("Dashboard:view", kwargs={"id": self.id})


class StringModel(models.Model):
    data = models.CharField(max_length=10485700)

Dashboard/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

from django.utils.timezone import now
# Create your models here.

from .models import *


class DataForm(forms.ModelForm):
    class Meta():
        model = DataModel
        fields = "__all__"


class RealTimeForm(forms.ModelForm):
    class Meta():
        model = RealTimeModel
        fields = "__all__"


class StringForm(forms.ModelForm):
    class Meta():
        model = StringModel
        fields = "__all__"

Dashboard/views.py
from django.shortcuts import render

from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse, StreamingHttpResponse, FileResponse, HttpResponse


from .models import *
from .forms import *

import time

import json

from google.protobuf import json_format
from .devices_pb2 import *

# Create your views here.


def home(req):
    return render(req, 'DashboardHome.html', {})


def view(req, id):
    obj = get_object_or_404(DataModel, id=id)
    obj.data = json.loads(obj.data)
    context = {
        "names": obj.data.keys(),
        "data": json.dumps(obj.data),
    }
    return render(req, 'Dashboard.html', context)


def set_data(req):
    if(req.method == "POST"):
        print(req.body)
        # dd = json.loads(req.body)
        # dd["object"]["data"] = str(dd["object"]["data"])
        # dd["object"]["data"] = dd["object"]["data"].replace("\'", "\"")
        # df = DataForm({"name": dd["object"]["name"], "data": dd["object"]["data"]})
        # if(df.is_valid()):
        #     df.save()

    return JsonResponse("{}", safe=False)


def get_data(req):
    if(req.method == "GET"):
        datas = DataModel.objects.all()
        for data in datas:
            d_j = json.loads(data.data)
            labels = []
            data = []
            max = 0
            for key in d_j.keys():
                for sub_key in d_j[key].keys():
                    labels.append(key + sub_key)
                    data.append([d_j[key][sub_key]])
                    if len([d_j[key][sub_key]][0]) > max:
                        max = len([d_j[key][sub_key]][0])

            x = []
            for i in range(0, max):
                x.append(i)
            return JsonResponse({"labels": labels, "data": data, "x": x})

    return JsonResponse("{}", safe=False)


def database(req):

    objs = DataModel.objects.all()

    context = {
        "data": objs
    }

    return render(req, "Database.html", context)


def real_time(req):

    obj = list(RealTimeModel.objects.all())[0]
    obj.data = json.loads(obj.data)
    context = {
        "realtime": True,
        "names": obj.data.keys(),
        "data": json.dumps(obj.data),
    }
    return render(req, "Dashboard.html", context)


def rt_get_data(req, sensor):
    sensor = sensor.replace("-", " ")
    obj = list(RealTimeModel.objects.all())[0]
    print(obj.timestamp)

    # data is string in json format, so load it
    d_j = json.loads(obj.data)
    d_j = d_j[str(sensor)]

    # setup labels and data arrays
    labels = []
    data = d_j

    # max count of elements to setup x axis
    max = 0
    for key in d_j.keys():
        labels.append(key)
        if len(d_j[key]) > max:
            max = len(d_j[key])
    print(labels)
    print(data)
    context = {
        "realtime": True,
        "names": [sensor],
        "data": json.dumps(d_j),
    }
    return JsonResponse(context, safe=False)


def rt_set_data(req):
    if(req.method == "POST"):
        chimera = Chimera()
        chimera.ParseFromString(req.body)
        j = json_format.MessageToJson(chimera)
        string_form = StringForm({"data": j})
        if(string_form.is_valid()):
            string_form.save()
            objs = StringModel.objects.all().delete()

    return JsonResponse("{}", safe=False)

Dashboard/templates/Dashboard.html
{%extends 'DashboardBase.html' %}

{% load static %}

{%block content%}

<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/hammer.js/2.0.8/hammer.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.1/Chart.bundle.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/chartjs-plugin-zoom/0.7.7/chartjs-plugin-zoom.js"></script>


<div class="masthead bg-primary text-white text-center">
  <h1 class="masthead-heading text-uppercase mb-0">Dashboard</h1>
</div>

<div class="container mt-4">
  {% for sensor in names %}
  <div class="row justify-content-center">
    <div class="col-md-6 col-lg-4" onclick="draw_graph('{{sensor}}')">
      <div class="portfolio-item mx-auto">
        <div class="portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100">
          <div class="portfolio-item-caption-content text-center text-white"><i class="fas fa-plus fa-3x"></i></div>
        </div>
        <div class="text-center c1">
          <h3>
            {{sensor}}
          </h3>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
</div>


<div id="Modal" class="modal">
  <div class="modal-content p-4">
    <div id="CloseModal" class="close flex-row ">
      <i class="fas fa-times fa-2x"></i>
    </div>
    <canvas id="chart"></canvas>
  </div>
</div>















<script>

  const socket = new WebSocket('ws://localhost:8000');

  var enableParsing = false;
  var graphName = null;

  // Chart
  var datasets = []
  var labels = [];
  var chart = null;

  var someColors = []

  socket.addEventListener('message', function (event) {
    if (enableParsing) {
      graphName = graphName.charAt(0).toLowerCase() + graphName.slice(1);
      graphName = graphName.replace(" ", "");

      var json = JSON.parse(event.data)
      var sensorData = json[graphName]

      var size = Object(sensorData).length
      var keys = [];
      if (size > 0) {
        keys = Object.keys(sensorData[0]);
      } else {
        return;
      }
      keys = keys.filter(el => el != "timestamp")

      labels = []
      datasets = []
      keys.forEach((element, i) => {
        newDataset = {
          label: element,
          data: [],
          borderColor: someColors[i],
          pointRadius: 0,
          backgroundColor: "rgba(0, 0, 0, 0.0)",
          // yAxisID: i == 0 ? "y" : "y" + i.toString(),
          yAxisID: "y"
        }
        datasets.push(newDataset)
      });

      // for each sensor object
      for (let el = 0; el < size; el++) {
        // for each sensor value of current object
        keys.forEach((element, i) => {
          datasets[i].data.push(sensorData[el][element])
        })
        labels.push(sensorData[el]["timestamp"])
      }

      if (chart == null) {
        create_graph(labels, datasets)
      } else {
        update_graph(labels, datasets)
        // create_graph(labels, datasets)
      }
    }
  });

  var dynamicColors = function () {
    var r = Math.floor(Math.random() * 255);
    var g = Math.floor(Math.random() * 255);
    var b = Math.floor(Math.random() * 255);
    return "rgb(" + r + "," + g + "," + b + ")";
  };

  for (let i = 0; i < 20; i++) {
    someColors.push(dynamicColors());
  }

  var modal = document.getElementById("Modal");
  var close = document.getElementById("CloseModal");

  function draw_graph(name) {
    // Show Modal
    modal.style.display = "block";

    // Set name and start receiving data
    graphName = name;
    enableParsing = true;

    if (chart != null) {
      chart.destroy()
      chart = null;
    }
  };

  function update_graph(labels, datasets) {
    if (chart == null)
      return

    var max_size = 1000;
    chart.data.labels.push(...labels);
    if (chart.data.labels.length > max_size) {
      chart.data.labels = chart.data.labels.slice(chart.data.labels.length - max_size, chart.data.labels.length);
    }
    for (index in chart.data.datasets) {
      chart.data.datasets[index].data.push(...datasets[index].data);

      if (chart.data.datasets[index].data.length > max_size) {
        chart.data.datasets[index].data = chart.data.datasets[index].data.slice(chart.data.datasets[index].data.length - max_size, chart.data.datasets[index].data.length);
      }
    }
    chart.update();
  }


  function create_graph(labels, datasets) {
    var $sensorChart = $("#chart");
    ctx = $sensorChart[0].getContext("2d");

    if (chart != null) {
      chart.destroy()
    }

    chart = new Chart(ctx, {
      type: 'line',
      data: {
        datasets: datasets,
        labels: labels
      },
      options: {
        animation: {
          duration: 10,
          x: true,
          y: false,
        },
        responsive: true,
        interaction: {
          mode: 'index',
          intersect: false,
        },
        stacked: false,
        plugins: {
          title: {
            display: true,
            text: 'Chart.js Line Chart - Multi Axis'
          }
        },
        scales: {
          yAxes: [
            {
              type: 'linear',
              display: true,
              position: 'left',
              id: 'y',
              ticks: {
                beginAtZero: true
              }
            },
          ]
        }
      }
    });
    for (var idx in datasets) {
      if (idx != 0)
        chart.getDatasetMeta(idx).hidden = true;
    }
  }

  close.onclick = function () {
    modal.style.display = "none";
    enableParsing = false;
    graphName = null
  }
</script>


{%endblock content%}

Dashboard/templates/DashboardHome.html
{%extends 'DashboardBase.html' %}

{% load static %}

{%block content%}

<div class="masthead bg-primary text-white text-center">
    <h1 class="masthead-heading text-uppercase mb-0">Dashboard</h1>
</div>


<div class="container d-flex align-items-center flex-column">
  <div class="container d-flex align-items-center justify-content-center flex-row mt-3r">
    <i class="fas fa-rocket fa-4x c6 m-2"></i>
    <a class="navbar-brand c6" href="{% url 'Dashboard:real-time' %}">Real Time</a>
  </div>
  <div class="container d-flex align-items-center justify-content-center flex-row mt-3r">
    <i class="fas fa-database fa-4x c2 m-2"></i>
    <a class=" justify-center navbar-brand c2" href="{% url 'Dashboard:database' %}">
      Database
    </a>
  </div>
</div>

<!--

<div class="row justify-content-center">
<div class="col-md-6 col-lg-4">
  <a class="nav-link py-3 px-0 px-lg-3 rounded"
      href="{% url 'JSONConfigurer:list-mission' %}">
    <div class="portfolio-item mx-auto">
        <div class="portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100">
            <div class="portfolio-item-caption-content text-center text-white"><i class="fas fa-plus fa-3x"></i></div>
        </div>
        <div class="text-center c1">
          <i class="fas fa-bolt fa-6x"></i>
          <h3>
            Mission
          </h3>
        </div>
    </div>
    </a>
</div>
-->

{%endblock content%}

Dashboard/templates/Database.html
{%extends 'DashboardBase.html' %}

{% load static %}

{%block content%}


<div class="container d-flex align-items-center flex-column">
  <div class="container d-flex align-items-center flex-column mt-3r">
    <a class="navbar-brand js-scroll-trigger" href="{% url 'Dashboard:home' %}"></a>
  </div>
</div>



<div class="container d-flex align-items-center flex-column">

  <div class="container d-flex align-items-center flex-column mt-3r">
    {% for dataset in data %}
    <a href="{{dataset.get_absolute_url}}">
      <h6>
        {{dataset.name}}
      </h6>
    </a>

    {% endfor %}

  </div>
</div>


{%endblock content%}